{
 "title": "Udacity CNDA Dashboards Project",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Prometheus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"default\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{workload_type=\"deployment\", workload=~\"backend-app|frontend-app\"}\n) by (workload)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=\"default\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{workload_type=\"deployment\", workload=~\"backend-app|frontend-app\"}\n) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Uptime ('frontend')",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(up{service=~\"frontend\"}) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Uptime ('backend')",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(up{service=~\"backend\"}) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "HTTP 4xx  Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    flask_http_request_duration_seconds_count{status=~\"4..\"}[30s]\n  ) \n) by (service, path)",
     "legendFormat": "{{service}} - {{path}}"
    }
   ]
  },
  {
   "title": "HTTP 5xx  Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    flask_http_request_duration_seconds_count{status=~\"5..\"}[30s]\n  ) \n) by (service, path)",
     "legendFormat": "{{service}} - {{path}}"
    }
   ]
  },
  {
   "title": "HTTP requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{status=\"200\"}[30s])",
     "legendFormat": "{{service}} - {{path}}"
    }
   ]
  },
  {
   "title": "Total requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "increase(flask_http_request_total[1m])",
     "legendFormat": "{{service}} -  HTTP {{status}}"
    }
   ]
  },
  {
   "title": "Average response time [30s]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{status=\"200\"}[30s])\n/\nrate(flask_http_request_duration_seconds_count{status=\"200\"}[30s])",
     "legendFormat": "{{service}}  -  {{path}}"
    }
   ]
  },
  {
   "title": "Requests under 100ms",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(\n  flask_http_request_duration_seconds_bucket{status=\"200\",le=\"0.1\"}[30s]\n)\n / ignoring (le)\nincrease(\n  flask_http_request_duration_seconds_count{status=\"200\"}[30s]\n)\n",
     "legendFormat": "{{service}}  -  {{path}}"
    }
   ]
  },
  {
   "title": "HTTP 5xx Errors % rate per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(increase(\n  flask_http_request_total{status=~\"5..\"}[1m]\n)) /\nsum(increase(\n  flask_http_request_total[1m]\n)) *100\n",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Jaeger", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Min latency ( backend '/api' )",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    { "service": "backend", "tags": "job_name=some_data_handler" }
   ]
  },
  {
   "title": "Requests Count by Latency ( backend '/api' )",
   "type": "histogram",
   "gridPos": { "h": 15, "w": 10, "x": 4, "y": 39 },
   "targets": [
    { "service": "backend", "tags": "job_name=some_data_handler" }
   ]
  },
  {
   "title": "Backend HTTP 500 Errors Count Indicator",
   "type": "histogram",
   "gridPos": { "h": 15, "w": 10, "x": 14, "y": 39 },
   "targets": [
    { "service": "backend", "tags": "http.status_code=500" }
   ]
  },
  {
   "title": "Avg latency ( backend '/api' )",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "service": "backend", "tags": "job_name=some_data_handler" }
   ]
  },
  {
   "title": "Max latency ( backend '/api' )",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "service": "backend", "tags": "job_name=some_data_handler" }
   ]
  }
 ]
}