{
 "title": "Udacity CNDA Dashboards Project / KPIs",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Uptime ('backend')",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(up{service=~\"backend\"}) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Average response time [30s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{status=\"200\"}[30s])\n/\nrate(flask_http_request_duration_seconds_count{status=\"200\"}[30s])",
     "legendFormat": "{{service}}  -  {{path}}"
    }
   ]
  },
  {
   "title": "HTTP 5xx Errors % rate per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(increase(\n  flask_http_request_total{status=~\"5..\"}[1m]\n)) /\nsum(increase(\n  flask_http_request_total[1m]\n)) *100\n",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}